[package]
name = "rust_search_helpers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_search_helpers"
crate-type = ["cdylib"]

[dependencies]
indicatif = "0.17.8"
pyo3 = "0.22.0"
